version: '3.8'

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    networks:
      - backend
    environment:
      DB_ADDR: postgres://admin:adminpassword@db:5432/social?sslmode=disable
    depends_on:
      - db
  db:
    image: postgres:16.3
    container_name: db
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    networks:
      - backend 
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
volumes:
  db-data:
networks:
  backend:
    driver: bridge